"""API-compliant validation for LogPoint Director.

Validates configurations against:
- CaC-ConfigMgr internal specs
- LogPoint Director API requirements
- Field types and required fields
- Cross-reference dependencies (by name, not ID)

IMPORTANT: Offline Validation vs API Apply
--------------------------------------------
This validator works in OFFLINE mode on desired state templates.
At this stage:
- IDs do NOT exist yet (generated by Director on creation)
- All references in YAML use NAMES (e.g., routing_policy: "rp-default")
- Cross-references are validated by NAME matching

During apply phase (future):
- API calls will map names to real Director IDs
- Payload transformation: name -> ID before POST/PUT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
import re


@dataclass
class ValidationError:
    """Single validation error."""
    resource_type: str
    resource_name: str
    field: str
    message: str
    severity: str = "ERROR"  # ERROR or WARNING
    api_doc: str = ""  # Link to API doc


class APIFieldValidator:
    """Validates fields against LogPoint Director API specs.
    
    All cross-reference validations use NAME matching, not ID matching.
    This is because:
    1. Templates reference resources by name (human-readable)
    2. IDs are only known after resources are created in Director
    3. Name-to-ID translation happens during apply phase with API calls
    """
    
    # API field specifications from API-REFERENCE.md
    API_SPECS = {
        "routing_policy": {
            "policy_name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$"},
            "catch_all": {"type": str, "required": True},
            "routing_criteria": {"type": list, "required": True},
        },
        "processing_policy": {
            "policy_name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$", "alias": "name"},
            "routing_policy": {"type": str, "required": True, "alias": "routingPolicy"},  # API uses camelCase
            "normalization_policy": {"type": str, "required": False, "alias": "normalizationPolicy"},
            "enrichment_policy": {"type": str, "required": False, "alias": "enrichmentPolicy"},
        },
        "normalization_policy": {
            "name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$"},
            "normalization_packages": {"type": list, "required": False},
            "compiled_normalizer": {"type": str, "required": False},
        },
        "enrichment_policy": {
            "name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$"},
            "specifications": {"type": list, "required": True},
        },
        "enrichment_specification": {
            "source": {"type": str, "required": True},
            "criteria": {"type": list, "required": True},
            "rules": {"type": list, "required": False},
        },
        "repo": {
            "name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$"},
            "hiddenrepopath": {"type": list, "required": False},  # Storage tiers
        },
        "hiddenrepopath": {
            "_id": {"type": str, "required": True},
            "path": {"type": str, "required": True},
            "retention": {"type": int, "required": True},
        },
        "device_group": {
            "name": {"type": str, "required": True, "pattern": r"^[a-zA-Z0-9_-]+$"},
            "description": {"type": str, "required": False},
            "criteria": {"type": list, "required": False},
        },
        "device": {
            "name": {"type": str, "required": True, "alias": "name"},
            "ip_address": {"type": str, "required": True, "alias": "ipAddress"},
            "device_group": {"type": str, "required": False, "alias": "deviceGroup"},
            "processing_policy": {"type": str, "required": False, "alias": "processingPolicy"},
            "collectors": {"type": list, "required": False},
            "enabled": {"type": bool, "required": False},
        },
    }
    
    def __init__(self, resources: dict[str, list[dict]]):
        """Initialize validator with resolved resources.
        
        Args:
            resources: Dict of resource type to list of resource dicts
        """
        self.resources = resources
        self.errors: list[ValidationError] = []
        
        # Build indexes for dependency checking (by name, not ID)
        self._indexes = self._build_indexes()
    
    def _build_indexes(self) -> dict[str, set[str]]:
        """Build name-based indexes for cross-reference validation.
        
        Note: All validations use resource NAMES, not IDs.
        IDs are only known after resources are created in Director.
        
        Returns:
            Dict mapping resource types to sets of resource names
        """
        indexes = {}
        
        # Name fields for each resource type
        name_fields = {
            "repos": "name",
            "routing_policies": "policy_name",
            "processing_policies": "policy_name",
            "normalization_policies": "name",
            "enrichment_policies": "name",
            "device_groups": "name",
            "devices": "name",
        }
        
        for resource_type, name_field in name_fields.items():
            indexes[resource_type] = {
                item.get(name_field) 
                for item in self.resources.get(resource_type, [])
                if item.get(name_field)
            }
        
        return indexes
    
    def validate_all(self) -> list[ValidationError]:
        """Run all validations.
        
        Returns:
            List of validation errors (empty if all valid)
        """
        self.errors = []
        
        # Validate each resource type
        self._validate_routing_policies()
        self._validate_processing_policies()
        self._validate_normalization_policies()
        self._validate_enrichment_policies()
        self._validate_repos()
        self._validate_device_groups()
        self._validate_devices()
        
        # Validate cross-references by name (not ID)
        self._validate_dependencies()
        
        return self.errors
    
    def _validate_routing_policies(self) -> None:
        """Validate routing policies against API spec."""
        spec = self.API_SPECS["routing_policy"]
        
        for rp in self.resources.get("routing_policies", []):
            rp_name = rp.get("policy_name", "unknown")
            
            # Check required fields
            for field, config in spec.items():
                if config["required"] and field not in rp:
                    self.errors.append(ValidationError(
                        resource_type="routing_policies",
                        resource_name=rp_name,
                        field=field,
                        message=f"Required field '{field}' is missing",
                        severity="ERROR",
                        api_doc="https://docs.logpoint.com/director/director-apis/director-console-api-documentation/routingpolicies"
                    ))
                elif field in rp:
                    # Check type (allow None for optional fields)
                    value = rp[field]
                    if value is None and not config.get("required", False):
                        continue  # None is allowed for optional fields (will be converted to "None")
                    
                    expected_type = config["type"]
                    if expected_type == str and not isinstance(value, str):
                        self.errors.append(ValidationError(
                            resource_type="routing_policies",
                            resource_name=rp_name,
                            field=field,
                            message=f"Field '{field}' should be string, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    elif expected_type == list and not isinstance(value, list):
                        self.errors.append(ValidationError(
                            resource_type="routing_policies",
                            resource_name=rp_name,
                            field=field,
                            message=f"Field '{field}' should be list, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    
                    # Check pattern
                    if "pattern" in config and isinstance(value, str):
                        if not re.match(config["pattern"], value):
                            self.errors.append(ValidationError(
                                resource_type="routing_policies",
                                resource_name=rp_name,
                                field=field,
                                message=f"Field '{field}' value '{value}' doesn't match pattern {config['pattern']}",
                                severity="ERROR"
                            ))
    
    def _validate_processing_policies(self) -> None:
        """Validate processing policies against API spec."""
        spec = self.API_SPECS["processing_policy"]
        
        for pp in self.resources.get("processing_policies", []):
            pp_name = pp.get("policy_name") or pp.get("name", "unknown")
            
            # Check required fields (using alias for API field names)
            for field, config in spec.items():
                field_name = config.get("alias", field)  # Use alias (camelCase) if defined
                
                # Check if field exists (either by field name or alias)
                field_exists = field in pp or field_name in pp
                
                if config["required"] and not field_exists:
                    self.errors.append(ValidationError(
                        resource_type="processing_policies",
                        resource_name=pp_name,
                        field=field,
                        message=f"Required field '{field}' ({field_name}) is missing",
                        severity="ERROR",
                        api_doc="https://docs.logpoint.com/director/director-apis/director-console-api-documentation/processingpolicy"
                    ))
                elif field_exists:
                    # Check type (allow None for optional fields)
                    # Use field name if exists, otherwise alias
                    value = pp.get(field, pp.get(field_name))
                    if value is None and not config.get("required", False):
                        continue  # None is allowed for optional fields (will be converted to "None")
                    
                    expected_type = config["type"]
                    if expected_type == str and not isinstance(value, str):
                        self.errors.append(ValidationError(
                            resource_type="processing_policies",
                            resource_name=pp_name,
                            field=field,
                            message=f"Field '{field}' should be string, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    
                    # Check pattern
                    if "pattern" in config and isinstance(value, str):
                        if not re.match(config["pattern"], value):
                            self.errors.append(ValidationError(
                                resource_type="processing_policies",
                                resource_name=pp_name,
                                field=field,
                                message=f"Field '{field}' value '{value}' doesn't match pattern {config['pattern']}",
                                severity="ERROR"
                            ))
    
    def _validate_normalization_policies(self) -> None:
        """Validate normalization policies against API spec."""
        spec = self.API_SPECS["normalization_policy"]
        
        for np in self.resources.get("normalization_policies", []):
            np_name = np.get("name", "unknown")
            
            for field, config in spec.items():
                if config["required"] and field not in np:
                    self.errors.append(ValidationError(
                        resource_type="normalization_policies",
                        resource_name=np_name,
                        field=field,
                        message=f"Required field '{field}' is missing",
                        severity="ERROR",
                        api_doc="https://docs.logpoint.com/director/director-apis/director-console-api-documentation/normalizationpolicy"
                    ))
                elif field in np and "pattern" in config:
                    value = np[field]
                    if isinstance(value, str) and not re.match(config["pattern"], value):
                        self.errors.append(ValidationError(
                            resource_type="normalization_policies",
                            resource_name=np_name,
                            field=field,
                            message=f"Field '{field}' value '{value}' doesn't match pattern {config['pattern']}",
                            severity="ERROR"
                        ))
    
    def _validate_enrichment_policies(self) -> None:
        """Validate enrichment policies against API spec."""
        spec = self.API_SPECS["enrichment_policy"]
        
        for ep in self.resources.get("enrichment_policies", []):
            ep_name = ep.get("name", "unknown")
            
            for field, config in spec.items():
                if config["required"] and field not in ep:
                    self.errors.append(ValidationError(
                        resource_type="enrichment_policies",
                        resource_name=ep_name,
                        field=field,
                        message=f"Required field '{field}' is missing",
                        severity="ERROR",
                        api_doc="https://docs.logpoint.com/director/director-apis/director-console-api-documentation/enrichmentpolicy"
                    ))
            
            # Validate specifications structure
            if "specifications" in ep:
                for i, spec_item in enumerate(ep["specifications"]):
                    self._validate_enrichment_specification(spec_item, ep_name, i)
    
    def _validate_enrichment_specification(self, spec: dict, ep_name: str, index: int) -> None:
        """Validate a single enrichment specification."""
        spec_def = self.API_SPECS["enrichment_specification"]
        
        for field, config in spec_def.items():
            if config["required"] and field not in spec:
                self.errors.append(ValidationError(
                    resource_type="enrichment_policies",
                    resource_name=f"{ep_name}.specifications[{index}]",
                    field=field,
                    message=f"Required field '{field}' is missing in specification",
                    severity="ERROR"
                ))
    
    def _validate_repos(self) -> None:
        """Validate repos against API spec."""
        spec = self.API_SPECS["repo"]
        tier_spec = self.API_SPECS["hiddenrepopath"]
        
        for repo in self.resources.get("repos", []):
            repo_name = repo.get("name", "unknown")
            
            for field, config in spec.items():
                if config["required"] and field not in repo:
                    self.errors.append(ValidationError(
                        resource_type="repos",
                        resource_name=repo_name,
                        field=field,
                        message=f"Required field '{field}' is missing",
                        severity="ERROR"
                    ))
                elif field in repo:
                    value = repo[field]
                    expected_type = config["type"]
                    if expected_type == int and not isinstance(value, int):
                        self.errors.append(ValidationError(
                            resource_type="repos",
                            resource_name=repo_name,
                            field=field,
                            message=f"Field '{field}' should be integer, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    
                    if "pattern" in config and isinstance(value, str):
                        if not re.match(config["pattern"], value):
                            self.errors.append(ValidationError(
                                resource_type="repos",
                                resource_name=repo_name,
                                field=field,
                                message=f"Field '{field}' value '{value}' doesn't match pattern {config['pattern']}",
                                severity="ERROR"
                            ))
            
            # Validate hiddenrepopath items
            for idx, tier in enumerate(repo.get("hiddenrepopath", [])):
                tier_id = tier.get("_id", f"[{idx}]")
                for field, config in tier_spec.items():
                    if config["required"]:
                        if field not in tier or tier[field] is None:
                            self.errors.append(ValidationError(
                                resource_type="repos",
                                resource_name=f"{repo_name}.hiddenrepopath[{tier_id}]",
                                field=field,
                                message=f"Required field '{field}' is missing or null in storage tier",
                                severity="ERROR"
                            ))
                        elif field in tier:
                            value = tier[field]
                            expected_type = config["type"]
                            if not isinstance(value, expected_type):
                                self.errors.append(ValidationError(
                                    resource_type="repos",
                                    resource_name=f"{repo_name}.hiddenrepopath[{tier_id}]",
                                    field=field,
                                    message=f"Field '{field}' should be {expected_type.__name__}, got {type(value).__name__}",
                                    severity="ERROR"
                                ))
    
    def _validate_device_groups(self) -> None:
        """Validate device groups against API spec."""
        spec = self.API_SPECS["device_group"]
        
        for dg in self.resources.get("device_groups", []):
            dg_name = dg.get("name", "unknown")
            
            for field, config in spec.items():
                if config["required"] and field not in dg:
                    self.errors.append(ValidationError(
                        resource_type="device_groups",
                        resource_name=dg_name,
                        field=field,
                        message=f"Required field '{field}' is missing",
                        severity="ERROR"
                    ))
                elif field in dg:
                    value = dg[field]
                    expected_type = config["type"]
                    if expected_type == str and not isinstance(value, str):
                        self.errors.append(ValidationError(
                            resource_type="device_groups",
                            resource_name=dg_name,
                            field=field,
                            message=f"Field '{field}' should be string, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    
                    if "pattern" in config and isinstance(value, str):
                        if not re.match(config["pattern"], value):
                            self.errors.append(ValidationError(
                                resource_type="device_groups",
                                resource_name=dg_name,
                                field=field,
                                message=f"Field '{field}' value '{value}' doesn't match pattern {config['pattern']}",
                                severity="ERROR"
                            ))
    
    def _validate_devices(self) -> None:
        """Validate devices against API spec."""
        spec = self.API_SPECS["device"]
        
        for device in self.resources.get("devices", []):
            device_name = device.get("name", "unknown")
            
            for field, config in spec.items():
                field_name = config.get("alias", field)
                
                if config["required"] and field_name not in device:
                    self.errors.append(ValidationError(
                        resource_type="devices",
                        resource_name=device_name,
                        field=field,
                        message=f"Required field '{field}' ({field_name}) is missing",
                        severity="ERROR"
                    ))
                elif field_name in device:
                    value = device[field_name]
                    if value is None and not config.get("required", False):
                        continue
                    
                    expected_type = config["type"]
                    if expected_type == str and not isinstance(value, str):
                        self.errors.append(ValidationError(
                            resource_type="devices",
                            resource_name=device_name,
                            field=field,
                            message=f"Field '{field}' should be string, got {type(value).__name__}",
                            severity="ERROR"
                        ))
                    elif expected_type == bool and not isinstance(value, bool):
                        self.errors.append(ValidationError(
                            resource_type="devices",
                            resource_name=device_name,
                            field=field,
                            message=f"Field '{field}' should be boolean, got {type(value).__name__}",
                            severity="ERROR"
                        ))
    
    def _validate_dependencies(self) -> None:
        """Validate cross-references between resources by NAME (not ID).
        
        CRITICAL: In offline mode (desired state), all references use NAMES.
        IDs are only known after resources are created in Director.
        
        During apply phase (future), name-to-ID translation will happen via API calls:
        1. GET /routingpolicies to get name->ID mapping
        2. Transform payload: routing_policy: "rp-default" -> "586cc3ed..."
        3. POST/PUT with real Director IDs
        """
        # Validate Processing Policy references (by name)
        for pp in self.resources.get("processing_policies", []):
            pp_name = pp.get("policy_name", "unknown")
            
            # Check routing_policy reference (by name, not ID)
            rp_ref = pp.get("routing_policy")
            if rp_ref and rp_ref != "None":
                # routing_policy is referenced by name in templates
                if rp_ref not in self._indexes.get("routing_policies", set()):
                    self.errors.append(ValidationError(
                        resource_type="processing_policies",
                        resource_name=pp_name,
                        field="routing_policy",
                        message=f"References non-existent Routing Policy: {rp_ref}",
                        severity="ERROR"
                    ))
            
            # Check normalization_policy reference (by name)
            np_ref = pp.get("normalization_policy")
            if np_ref and np_ref != "None":
                if np_ref not in self._indexes.get("normalization_policies", set()):
                    self.errors.append(ValidationError(
                        resource_type="processing_policies",
                        resource_name=pp_name,
                        field="normalization_policy",
                        message=f"References non-existent Normalization Policy: {np_ref}",
                        severity="ERROR"
                    ))
            
            # Check enrichment_policy reference (by name, not ID)
            ep_ref = pp.get("enrichment_policy")
            if ep_ref and ep_ref != "None":
                # enrichment_policy is referenced by name in templates
                if ep_ref not in self._indexes.get("enrichment_policies", set()):
                    self.errors.append(ValidationError(
                        resource_type="processing_policies",
                        resource_name=pp_name,
                        field="enrichment_policy",
                        message=f"References non-existent Enrichment Policy: {ep_ref}",
                        severity="ERROR"
                    ))
        
        # Validate Routing Policy catch_all references (by name)
        for rp in self.resources.get("routing_policies", []):
            rp_name = rp.get("policy_name", "unknown")
            
            catch_all = rp.get("catch_all")
            if catch_all:
                if catch_all not in self._indexes.get("repos", set()):
                    self.errors.append(ValidationError(
                        resource_type="routing_policies",
                        resource_name=rp_name,
                        field="catch_all",
                        message=f"References non-existent Repo: {catch_all}",
                        severity="ERROR"
                    ))
            
            # Check routing_criteria repo references (by name)
            for criterion in rp.get("routing_criteria", []):
                repo_ref = criterion.get("repo")
                if repo_ref and repo_ref not in self._indexes.get("repos", set()):
                    self.errors.append(ValidationError(
                        resource_type="routing_policies",
                        resource_name=rp_name,
                        field="routing_criteria.repo",
                        message=f"Criterion references non-existent Repo: {repo_ref}",
                        severity="ERROR"
                    ))
        
        # Validate Device references (by name)
        for device in self.resources.get("devices", []):
            device_name = device.get("name", "unknown")
            
            # Check device_group reference
            dg_ref = device.get("deviceGroup")
            if dg_ref and dg_ref not in self._indexes.get("device_groups", set()):
                self.errors.append(ValidationError(
                    resource_type="devices",
                    resource_name=device_name,
                    field="deviceGroup",
                    message=f"References non-existent Device Group: {dg_ref}",
                    severity="ERROR"
                ))
            
            # Check processing_policy reference
            pp_ref = device.get("processingPolicy")
            if pp_ref and pp_ref not in self._indexes.get("processing_policies", set()):
                self.errors.append(ValidationError(
                    resource_type="devices",
                    resource_name=device_name,
                    field="processingPolicy",
                    message=f"References non-existent Processing Policy: {pp_ref}",
                    severity="ERROR"
                ))
    
    def print_report(self) -> None:
        """Print validation report."""
        if not self.errors:
            print("✅ All API validations passed")
            return
        
        errors = [e for e in self.errors if e.severity == "ERROR"]
        warnings = [e for e in self.errors if e.severity == "WARNING"]
        
        if errors:
            print(f"\n❌ {len(errors)} API validation error(s):")
            for e in errors:
                print(f"  • [{e.resource_type}.{e.resource_name}] {e.field}: {e.message}")
                if e.api_doc:
                    print(f"    Doc: {e.api_doc}")
        
        if warnings:
            print(f"\n⚠️  {len(warnings)} warning(s):")
            for e in warnings:
                print(f"  • [{e.resource_type}.{e.resource_name}] {e.field}: {e.message}")


def validate_api_compliance(resources: dict[str, list[dict]]) -> list[ValidationError]:
    """Quick validation function.
    
    Note: All cross-reference validations use NAME matching, not ID matching.
    IDs are only known after resources are created in Director.
    
    Args:
        resources: Resolved resources
        
    Returns:
        List of validation errors
    """
    validator = APIFieldValidator(resources)
    return validator.validate_all()
