"""API-compliant validation for LogPoint configurations.

Validates configurations against provider-specific API requirements.

IMPORTANT: Offline Validation vs API Apply
--------------------------------------------
This validator works in OFFLINE mode on desired state templates.
At this stage:
- IDs do NOT exist yet (generated by API on creation)
- All references in YAML use NAMES (e.g., routing_policy: "rp-default")
- Cross-references are validated by NAME matching

During apply phase:
- API calls will map names to real IDs via the provider's NameToIDResolver
- Payload transformation: name -> ID before POST/PUT

Multi-Provider Support
----------------------
The validator is provider-agnostic. It uses an APIConvention to know:
- Field naming conventions (camelCase vs snake_case)
- Required fields and types
- Resource-specific name fields
- Cross-reference rules

Example:
    from cac_configmgr.providers.conventions import DirectorAPIConvention
    
    convention = DirectorAPIConvention()
    validator = APIFieldValidator(resources, convention)
    errors = validator.validate_all()
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cac_configmgr.core.conventions import APIConvention, FieldSpec


@dataclass
class ValidationError:
    """Single validation error."""
    resource_type: str
    resource_name: str
    field: str
    message: str
    severity: str = "ERROR"  # ERROR or WARNING
    api_doc: str = ""  # Link to API doc


class APIFieldValidator:
    """Validates configurations against API specs via APIConvention.
    
    This validator is provider-agnostic. It delegates provider-specific
    decisions (field names, types, patterns) to the injected APIConvention.
    
    Example:
        from cac_configmgr.providers.conventions import DirectorAPIConvention
        
        convention = DirectorAPIConvention()
        validator = APIFieldValidator(resources, convention)
        errors = validator.validate_all()
    """
    
    def __init__(self, resources: dict[str, list[dict]], convention: APIConvention):
        """Initialize validator with resources and convention.
        
        Args:
            resources: Dict of resource type to list of resource dicts
            convention: APIConvention implementation (e.g., DirectorAPIConvention)
        """
        self.resources = resources
        self.convention = convention
        self.errors: list[ValidationError] = []
        
        # Build indexes for dependency checking (by name, not ID)
        self._indexes = self._build_indexes()
    
    def _build_indexes(self) -> dict[str, set[str]]:
        """Build name-based indexes for cross-reference validation.
        
        Note: All validations use resource NAMES, not IDs.
        IDs are only known after resources are created.
        
        Returns:
            Dict mapping resource types to sets of resource names
        """
        indexes = {}
        
        for resource_type in self.convention.get_supported_resources():
            name_field = self.convention.get_name_field(resource_type)
            indexes[resource_type] = {
                item.get(name_field)
                for item in self.resources.get(resource_type, [])
                if item.get(name_field)
            }
        
        return indexes
    
    def validate_all(self) -> list[ValidationError]:
        """Run all validations.
        
        Returns:
            List of validation errors (empty if all valid)
        """
        self.errors = []
        
        # Validate each supported resource type
        for resource_type in self.convention.get_supported_resources():
            if resource_type in self.resources:
                self._validate_resource_type(resource_type)
        
        # Validate cross-references via convention rules
        self._validate_cross_references()
        
        return self.errors
    
    def _validate_resource_type(self, resource_type: str) -> None:
        """Validate all resources of a given type.
        
        Args:
            resource_type: Type of resource to validate
        """
        spec = self.convention.get_resource_spec(resource_type)
        if not spec:
            return  # Unknown resource type
        
        for resource in self.resources.get(resource_type, []):
            self._validate_resource(resource_type, resource, spec)
    
    def _validate_resource(
        self, 
        resource_type: str, 
        resource: dict, 
        spec
    ) -> None:
        """Validate a single resource against its spec.
        
        Args:
            resource_type: Type of resource
            resource: Resource data dictionary
            spec: ResourceSpec for this resource type
        """
        resource_name = resource.get(spec.name_field, "unknown")
        
        for field_name, field_spec in spec.fields.items():
            self._validate_field(
                resource_type=resource_type,
                resource_name=resource_name,
                resource=resource,
                field_name=field_name,
                field_spec=field_spec,
            )
    
    def _validate_field(
        self,
        resource_type: str,
        resource_name: str,
        resource: dict,
        field_name: str,
        field_spec: FieldSpec,
    ) -> None:
        """Validate a single field.
        
        Args:
            resource_type: Type of resource
            resource_name: Name of the resource
            resource: Resource data dictionary
            field_name: Internal field name
            field_spec: FieldSpec with validation rules
        """
        # Check if field exists (by internal name or alias)
        api_field_name = field_spec.alias or field_name
        field_exists = field_name in resource or api_field_name in resource
        
        # Check required
        if field_spec.required and not field_exists:
            self.errors.append(ValidationError(
                resource_type=resource_type,
                resource_name=resource_name,
                field=field_name,
                message=f"Required field '{field_name}' ({api_field_name}) is missing",
                severity="ERROR",
                api_doc=field_spec.api_doc,
            ))
            return
        
        if not field_exists:
            return  # Optional field not present
        
        # Get field value (prefer internal name, fallback to alias)
        value = resource.get(field_name, resource.get(api_field_name))
        
        # Allow None for optional fields
        if value is None and not field_spec.required:
            return
        
        # Check type
        if field_spec.type and not isinstance(value, field_spec.type):
            self.errors.append(ValidationError(
                resource_type=resource_type,
                resource_name=resource_name,
                field=field_name,
                message=(
                    f"Field '{field_name}' should be {field_spec.type.__name__}, "
                    f"got {type(value).__name__}"
                ),
                severity="ERROR",
                api_doc=field_spec.api_doc,
            ))
        
        # Check pattern (strings only)
        if field_spec.pattern and isinstance(value, str):
            if not re.match(field_spec.pattern, value):
                self.errors.append(ValidationError(
                    resource_type=resource_type,
                    resource_name=resource_name,
                    field=field_name,
                    message=(
                        f"Field '{field_name}' value '{value}' doesn't match "
                        f"pattern {field_spec.pattern}"
                    ),
                    severity="ERROR",
                    api_doc=field_spec.api_doc,
                ))
    
    def _validate_cross_references(self) -> None:
        """Validate cross-references between resources.
        
        Uses the cross-reference rules from the APIConvention.
        All validations use resource NAMES, not IDs.
        """
        rules = self.convention.get_cross_reference_validations()
        
        for rule in rules:
            for resource in self.resources.get(rule.source_type, []):
                self._validate_cross_reference_rule(resource, rule)
    
    def _validate_cross_reference_rule(
        self, 
        resource: dict, 
        rule
    ) -> None:
        """Validate a single cross-reference rule against a resource.
        
        Args:
            resource: Resource to validate
            rule: CrossReferenceRule to apply
        """
        # Get source resource name for error messages
        source_name_field = self.convention.get_name_field(rule.source_type)
        source_name = resource.get(source_name_field, "unknown")
        
        # Handle nested fields (e.g., "routing_criteria.repo")
        if "." in rule.source_field:
            self._validate_nested_cross_reference(resource, rule, source_name)
            return
        
        # Get the referenced value
        ref_value = resource.get(rule.source_field)
        
        # Allow None if configured
        if ref_value is None or ref_value == "None":
            if rule.allow_none:
                return
            else:
                self.errors.append(ValidationError(
                    resource_type=rule.source_type,
                    resource_name=source_name,
                    field=rule.source_field,
                    message=f"Required reference to {rule.target_type} is missing",
                    severity="ERROR",
                ))
                return
        
        # Check if referenced resource exists
        if ref_value not in self._indexes.get(rule.target_type, set()):
            self.errors.append(ValidationError(
                resource_type=rule.source_type,
                resource_name=source_name,
                field=rule.source_field,
                message=f"References non-existent {rule.target_type}: {ref_value}",
                severity="ERROR",
            ))
    
    def _validate_nested_cross_reference(
        self,
        resource: dict,
        rule,
        source_name: str,
    ) -> None:
        """Validate cross-references in nested structures.
        
        Handles cases like routing_criteria.repo where routing_criteria
        is a list and each item has a repo field.
        
        Args:
            resource: Resource to validate
            rule: CrossReferenceRule with nested field path
            source_name: Name of source resource for error messages
        """
        parts = rule.source_field.split(".")
        parent_field = parts[0]
        child_field = parts[1]
        
        parent_value = resource.get(parent_field)
        if not parent_value or not isinstance(parent_value, list):
            return
        
        for i, item in enumerate(parent_value):
            ref_value = item.get(child_field) if isinstance(item, dict) else None
            
            if not ref_value:
                continue
            
            if ref_value not in self._indexes.get(rule.target_type, set()):
                self.errors.append(ValidationError(
                    resource_type=rule.source_type,
                    resource_name=source_name,
                    field=f"{parent_field}[{i}].{child_field}",
                    message=f"References non-existent {rule.target_type}: {ref_value}",
                    severity="ERROR",
                ))
    
    def print_report(self) -> None:
        """Print validation report."""
        if not self.errors:
            print("✅ All API validations passed")
            return
        
        errors = [e for e in self.errors if e.severity == "ERROR"]
        warnings = [e for e in self.errors if e.severity == "WARNING"]
        
        if errors:
            print(f"\n❌ {len(errors)} API validation error(s):")
            for e in errors:
                print(f"  • [{e.resource_type}.{e.resource_name}] {e.field}: {e.message}")
                if e.api_doc:
                    print(f"    Doc: {e.api_doc}")
        
        if warnings:
            print(f"\n⚠️  {len(warnings)} warning(s):")
            for e in warnings:
                print(f"  • [{e.resource_type}.{e.resource_name}] {e.field}: {e.message}")


def validate_api_compliance(
    resources: dict[str, list[dict]], 
    convention: APIConvention | None = None
) -> list[ValidationError]:
    """Quick validation function with optional convention.
    
    Note: All cross-reference validations use NAME matching, not ID matching.
    IDs are only known after resources are created.
    
    Args:
        resources: Resolved resources
        convention: APIConvention to use (defaults to DirectorAPIConvention)
        
    Returns:
        List of validation errors
        
    Example:
        # Default Director convention
        errors = validate_api_compliance(resources)
        
        # Custom convention
        from cac_configmgr.providers.conventions import DirectorAPIConvention
        errors = validate_api_compliance(resources, DirectorAPIConvention())
    """
    if convention is None:
        # Default to Director convention for backward compatibility
        from cac_configmgr.providers.conventions import DirectorAPIConvention
        convention = DirectorAPIConvention()
    
    validator = APIFieldValidator(resources, convention)
    return validator.validate_all()
